---
blank_issues_enabled: true
contact_links:
  - name: Documentation for the Go library.
    url: https://pkg.go.dev/github.com/northwood-labs/devsec-tools/pkg
    about: Read Go library documentation.
