---
services:
  db:
    container_name: localdev-valkey
    build:
      context: .
      dockerfile: Dockerfile-valkey

    # set shared memory limit when using docker-compose
    shm_size: 512mb
    restart: always
    privileged: true
    pid: host
    sysctls:
      net.core.somaxconn: 1024

    volumes:
      - vkdata:/data
    ports:
      - 6379:6379

volumes:
  vkdata:
    driver: local

networks:
  dst-network:
    driver: bridge
