# syntax=docker/dockerfile:1
FROM golang@sha256:aee43c3ccbf24fdffb7295693b6e33b21e01baec1b2a55acc351fde345e9ec34
# docker.io/golang:1.25-alpine

WORKDIR /api-proxy

ENTRYPOINT ["./apiproxy-entrypoint.sh"]
