# syntax=docker/dockerfile:1
FROM valkey/valkey@sha256:a560291eda3595674847834defff40887e27051c7ecf1afcd0c7ee89168e8e2f
# docker.io/valkey/valkey:8

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
