# syntax=docker/dockerfile:1
FROM golang@sha256:2d40d4fc278dad38be0777d5e2a88a2c6dee51b0b29c97a764fc6c6a11ca893c AS go-installer
# docker.io/golang:1.24-alpine

# Download the AWS Lambda Runtime Interface Emulator
RUN go install github.com/northwood-labs/download-asset@latest
RUN --mount=type=secret,id=github_token \
    GITHUB_TOKEN="$(cat /run/secrets/github_token)" \
    download-asset get \
        --owner-repo aws/aws-lambda-runtime-interface-emulator \
        --tag latest \
        --intel64 x86_64 \
        --arm64 arm64 \
        --pattern 'aws-lambda-rie-{{.Arch}}' \
        --write-to-bin aws-lambda-rie \
    ;

RUN mv /usr/local/bin/aws-lambda-rie* /usr/local/bin/aws-lambda-rie

# Build Delve for debugging
RUN go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

#-------------------------------------------------------------------------------

# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/provided@sha256:2accac96d3e2da0efbd64d436c7c938e911842f5a335176b66127595fc0aea4e
# docker pull public.ecr.aws/lambda/provided:al2023
# docker images --digests public.ecr.aws/lambda/provided:al2023 --format '{{ .Digest }}'

COPY --from=go-installer /usr/local/bin/aws-lambda-rie /usr/local/bin/aws-lambda-rie
COPY --from=go-installer /go/bin/dlv /dlv
COPY lambda-entrypoint.sh /entrypoint.sh

RUN chmod 0755 /usr/local/bin/aws-lambda-rie /entrypoint.sh

EXPOSE 42424

ENTRYPOINT ["/entrypoint.sh"]
