---
# This syntax is what Traefik refers to as "dynamic" configuration. "Static"
# configuration has a different shape.

http:
  routers:
    hugo:
      rule: "Host(`devsec.local`)"
      priority: 1001
      entryPoints:
        - web
        - websecure
      service: hugo
      middlewares: # Executes in order
        - cors
        - hugo
    traefikdash:
      rule: "Host(`traefik.devsec.local`)"
      priority: 1002
      entryPoints:
        - web
        - websecure
      service: traefikdash
      middlewares: # Executes in order
        - traefikdash

  middlewares:
    hugo:
      # https://doc.traefik.io/traefik/middlewares/http/redirectregex/
      redirectRegex:
        regex: "^http://devsec.local(.*)"
        replacement: "http://devsec.local:1313${1}"
        permanent: false
    traefikdash:
      # https://doc.traefik.io/traefik/middlewares/http/redirectregex/
      redirectRegex:
        regex: "^http://traefik.devsec.local(.*)"
        replacement: "http://traefik.devsec.local:8082${1}"
        permanent: false
    cors:
      # https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - POST
        accessControlAllowHeaders:
          - Origin
        accessControlAllowOriginList: "*"
        accessControlExposeHeaders:
          - Content-Length
        accessControlMaxAge: 43200
        addVaryHeader: true

  services:
    hugo:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:1313
        passHostHeader: false
    traefikdash:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8082
        passHostHeader: false
