.nh
.TH "devsec-tools" "1" "Feb 2024" "" ""

.SH NAME
.PP
devsec-tools - A set of useful tools for DevSecOps workflows.


.SH SYNOPSIS
.PP
\fBdevsec-tools [flags]\fP


.SH DESCRIPTION
.PP
DevSec Tools is a suite of tools that are useful for DevSecOps workflows.
Its goal is to simplify and streamline the process of developing,
securing, and operating software and systems for the web.

.PP
You can also find these tools online at https://devsec.tools.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for devsec-tools

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Disable all logging output.

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output.


.SH SEE ALSO
.PP
\fBdevsec-tools-completion(1)\fP, \fBdevsec-tools-dockerfile-hasher(1)\fP, \fBdevsec-tools-version(1)\fP
